// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGBViagens.Models;

#nullable disable

namespace RGBViagens.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211220132735_bancoRGB")]
    partial class bancoRGB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RGBViagens.Models.ComprarDestinos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Destinos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ida")
                        .HasColumnType("datetime2");

                    b.Property<int>("N_Passageiros")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Volta")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ID_Destinos");

                    b.ToTable("ComprarDestinos");
                });

            modelBuilder.Entity("RGBViagens.Models.Contato", b =>
                {
                    b.Property<int>("ID_Contato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Contato"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Contato");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("RGBViagens.Models.Destinos", b =>
                {
                    b.Property<int>("ID_Destinos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Destinos"), 1L, 1);

                    b.Property<string>("Nome_lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preco_Promoção")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Destinos");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("RGBViagens.Models.ComprarDestinos", b =>
                {
                    b.HasOne("RGBViagens.Models.Destinos", "Destinos")
                        .WithMany("ComprarDestinos")
                        .HasForeignKey("ID_Destinos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("RGBViagens.Models.Destinos", b =>
                {
                    b.Navigation("ComprarDestinos");
                });
#pragma warning restore 612, 618
        }
    }
}
